### ISSUE TITLE
CSS: h2 code font-size

### ISSUE THREAD

**Issue by westurner** [jakevdp/PythonDataScienceHandbook#247]
`<code>` tags in headers are comparatively small. Something like this would fix it:

```css
/*
h2 {
    font-size: 30px;
}
article code {
    font-size: 13px;
}
*/
h2 code {
   font-size: 28px;
}
/* ... h* code { font-size: } */
```
